linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - exhaustive
    - gofmt
    - goheader
    - gosec
    - govet
    - ineffassign
    - misspell
    - noctx
    - paralleltest
    - prealloc
    - staticcheck
    - typecheck
    - unused
    - varcheck