repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.3.5
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: golangci-lint
    - id: go-unit-tests
