apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  name: ocsp-l2-cache
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ocsp-l2-cache
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ocsp-l2-cache
    spec:
      containers:
      - name: ocsp-l2-cache
        image: docker.io/jcjones/ocsp-l2-cache:latest
        imagePullPolicy: Always
        ports:
        - name: liveness-port
          containerPort: 8080
          hostPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          initialDelaySeconds: 60
          periodSeconds: 60
        resources:
          requests:
            cpu: 4
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 120
status:
  availableReplicas: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
